name: Infinity_Travel FrontEnd CI/CD

on:
    push:
        branches: ["release"]
    pull_request:
        branches: ["release"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 프론트엔드 배포
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      set -e
                      cd /home/ubuntu/Infinity_Travel_FE
                      git pull
